platform :ios, '8.0'
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'StarLib_Example' do
    
  pod 'StarLib', :path => '../'

  target 'StarLib_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end


